version: '3.8'

services:
  postgresql:
    image: postgres:13
    env_file:
      - .env.docker.local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env.docker.local
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgresql:
        condition: service_healthy
    command: sh -c "./init_db.sh $DATABASE_URL $POSTGRES_USER && npm run prisma:migrate:prod && npm run start:prod"

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  postgres_data:
