export enum AcaoEnum {
  VISUALIZA_EMPRESAS = 1,
  VISUALIZA_UNIDADES,
  MODIFICA_BLOCO_PROFESSOR,
  MODIFICA_SALA_AULA,
  EDITAR_DESCONTO,
  APROVAR_SPC,
  GERAR_DESCONTO,
  INCLUIR,
  EDITAR,
  EXCLUIR,
  LISTAGEM_NOVO,
  VISUALIZA_TELA,
}
